# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        TradeBundle\Entity\Usuario: bcrypt
    
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: TradeBundle\Entity\Usuario
                property: username
        in_memory:
            memory: ~    

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~ 
            provider: our_db_provider
            access_denied_url: /
            form_login:
                login_path: login
                check_path: login
            logout_on_user_change: true
            logout:
                path: /logout   
                target: /trade/

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/car, roles: ROLE_USER }
